
#include <iostream>
#include <cmath>
#include <string>
using namespace std ;

/*
THERE ARE MANY TYPES DATA FOR C++
1  INTEGRAL  LIKE  INT  AND CHAR  (NUMBER AND LETTERS A TO Z)
2  FLOATING  TYPE
3  BOOLEAN  LIKE  TRUE AND FALSE  (0 AND 1 )
4  STRING   LIKE TEXT  ("NADER OR MOHMED ")
5  VOID  TYPE  LIKE EMPTY
6  WIDE CHARACTER  UNICODE  LIKE LANGUAGES ARABIC CHINESS
*/

/*
THERE ARE MORE  DATA TYPES  LIKE  IT IS NAME DERIVED DATATYPE
1 ARRAY
2 FUNCTION
3 POINTER
4 REFRENCES

*/

/*
THERE ARE MORE  DATA TYPES  LIKE  IT IS NAME DERIVED USER DATATYPE
1 CLASS
2 ENUM
3 STRUCTER
4 UNION
5 DEF TYPE

*/
int main() {
   

   cout<<"M1\\M2\\M3"<<endl ;
   cout<<"My full name is \" Nader \" "<<endl  ;

  char  char1  = 'A'  ;
  cout<<"\n the character is "<<char1 <<endl ;
cout<<"\a" <<endl ;


     cout<<"\n" ;
    return 0;
}
